[pytest]
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v -s --alluredir=./reports/allure-results -m "not mock"
markers =
    mock: 标记为 Mock 环境的测试用例，在真实环境中排除